config/routes.rb
Rails.application.routes.draw do
  resources :save_states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/save_state.rb
class SaveState < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/save_states_controller.rb
class SaveStatesController < ApplicationController
  before_action :set_save_state, only: %i[ show edit update destroy ]

  # GET /save_states or /save_states.json
  def index
    @save_states = SaveState.all
  end

  # GET /save_states/1 or /save_states/1.json
  def show
  end

  # GET /save_states/new
  def new
    @save_state = SaveState.new
  end

  # GET /save_states/1/edit
  def edit
  end

  # POST /save_states or /save_states.json
  def create
    @save_state = SaveState.new(save_state_params)

    respond_to do |format|
      if @save_state.save
        format.html { redirect_to save_state_url(@save_state), notice: "Save state was successfully created." }
        format.json { render :show, status: :created, location: @save_state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @save_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /save_states/1 or /save_states/1.json
  def update
    respond_to do |format|
      if @save_state.update(save_state_params)
        format.html { redirect_to save_state_url(@save_state), notice: "Save state was successfully updated." }
        format.json { render :show, status: :ok, location: @save_state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @save_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /save_states/1 or /save_states/1.json
  def destroy
    @save_state.destroy!

    respond_to do |format|
      format.html { redirect_to save_states_url, notice: "Save state was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_save_state
      @save_state = SaveState.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def save_state_params
      params.require(:save_state).permit(:encoded_string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/save_states_helper.rb
module SaveStatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookiecalc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/save_states/_form.html.erb
<%= form_with(model: save_state) do |form| %>
  <% if save_state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(save_state.errors.count, "error") %> prohibited this save_state from being saved:</h2>

      <ul>
        <% save_state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encoded_string, style: "display: block" %>
    <%= form.text_field :encoded_string %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/save_states/_save_state.html.erb
<div id="<%= dom_id save_state %>">
  <p>
    <strong>Encoded string:</strong>
    <%= save_state.encoded_string %>
  </p>

</div>

app/views/save_states/edit.html.erb
<% content_for :title, "Editing save state" %>

<h1>Editing save state</h1>

<%= render "form", save_state: @save_state %>

<br>

<div>
  <%= link_to "Show this save state", @save_state %> |
  <%= link_to "Back to save states", save_states_path %>
</div>

app/views/save_states/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Save states" %>

<h1>Save states</h1>

<div id="save_states">
  <% @save_states.each do |save_state| %>
    <%= render save_state %>
    <p>
      <%= link_to "Show this save state", save_state %>
    </p>
  <% end %>
</div>

<%= link_to "New save state", new_save_state_path %>

app/views/save_states/new.html.erb
<% content_for :title, "New save state" %>

<h1>New save state</h1>

<%= render "form", save_state: @save_state %>

<br>

<div>
  <%= link_to "Back to save states", save_states_path %>
</div>

app/views/save_states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @save_state %>

<div>
  <%= link_to "Edit this save state", edit_save_state_path(@save_state) %> |
  <%= link_to "Back to save states", save_states_path %>

  <%= button_to "Destroy this save state", @save_state, method: :delete %>
</div>